### ISSUE TITLE
C++ SDK: should embrace moving by value where applicable

### ISSUE THREAD

**Issue by cthulhu-irl** [trytouca/trytouca#107]
Touca's C++ SDK contains a lot of const& arguments where value that are passed to them are later stored in a container, and this approach picks up copy constructor instead of move constructor, most of the times with both an allocation and copy overhead.

`data_point`/`object`/`array` as examples of such containers are already supporting move construction and assignment.

These types are also at the core of cpp-sdk and have potentially great impact on performance of the sdk.

I'm suggesting to identify and embrace moving instead anywhere desired.

**Comment by ghorbanzade** [comment]
We've moving this task to our internal issue tracking system. Closing to prevent duplication.
