### ISSUE TITLE
Add basic regression test for the data ingestion workflow

### ISSUE THREAD

**Issue by cthulhu-irl** [trytouca/trytouca#109]
Touca is providing regression testing, but as a multi-component and multi-service platform, it's not regression tested.

As a contributor unfamiliar with the whole project, I suspect how my changes might reflect to the whole platform.

Also testing touca with itself as an open source platform is a real world example and demonstration, both for clients and contributors.

**Comment by ghorbanzade** [comment]
We've moved this task to our internal issue tracking system. Closing to prevent duplication.
