### ISSUE TITLE
JavaScript SDK: Split runner into separate package

### ISSUE THREAD

**Issue by ghorbanzade** [trytouca/trytouca#194]
Currently, our JavaScript SDK comes in one single package `@touca/node` with dependencies on `fs`, `path`, `http`, `https`, and `url` node modules. This prohibits using the SDK in environments where node is not available. In addition, the SDK comes includes a test framework that is responsible for taking command line arguments and reporting the outcome of the test through the standard output. We rely on dependencies such as `yargs` and `chalk` to perform these operations.

We'd like to split `@touca/node` into packages `@touca/core` and `@touca/cli` and move the test framework and other extra SDK functionalities into the `@touca/cli` package, making `@touca/core` suitable for a variety of environments.

**Comment by Shervin1995** [comment]
Hi @ghorbanzade ! thanks for simplifying the issue for beginners. I like to contribute! please help me!

**Comment by ghorbanzade** [comment]
Of course! That's great to hear and thank you so much for your interest. Is there anything in particular regarding this issue that you need help with? You are also welcome to ask questions and chat in the #contributing channel on our Discord. 🙏🏼

**Comment by Shervin1995** [comment]
As this is my first contribute experience, don't know how to do it. 
1. I forked this repo
2. I cloned the forked repo
3. now what to do? 

I guess I should go to `\trytouca\sdk\js\packages\node` and hit `yarn install` to install dependencies at first.

**Comment by ghorbanzade** [comment]
Aha. No problem and you are totally right to be confused. We should have better docs explaining Touca project structure and how to setup your development environment for make changes. Let me see if I can publish them tomorrow. Hopefully they should help answer some of your questions.

**Comment by ghorbanzade** [comment]
Moving this task to our internal issue tracking system. Closing to prevent duplication.
