### ISSUE TITLE
Touca Cloud Web App shows failure when creating suite

### ISSUE THREAD

**Issue by rmarrcode** [trytouca/trytouca#81]
## Description

Creating a new suite results in the error: 'Something went wrong. Please try this operation again at a later time' despite the suite being created. 

## Environment

I'm using ubuntu 18.04.05

## Steps To Reproduce

Create a new suite

**Comment by ghorbanzade** [comment]
Thank you @rmarrcode once again for finding this bug, reporting it, and creating an issue for it. It appears #128 fixes this issue. Could you try and confirm that you no longer see this error message?

**Comment by ghorbanzade** [comment]
Received confirmation on [Discord](https://touca.io/discord) that issue is now fixed.
